[tool.bumpversion]
current_version = "1.0.2"
commit = true
message = "Bump version v{current_version} -> v{new_version}"

[[tool.bumpversion.files]]
filename = "package.json"
search = "\"version\": \"{current_version}\""
replace = "\"version\": \"{new_version}\""
